---
title: "NLP poetry generator"
contributors: "Disha Hauzaree, Caroline He, Christopher LaBorde, Lyndsey Umsted"
date: "2022-11-30"
output: html_document
---

#Description
Vignette on using markov chains to create a poetry generator based on particular poetry genres/styles; created as a class project for PSTAT197A in Fall 2022.

#Vignette abstract
The topic of this vignette is related to using NLPs to train a poetry generator based on the type of particular authors. To do this, we used a markov chain model on a subset of data from the Project Gutenberg database, which is a digital database of written works categorized by genre, author, etc. This vignette consists of a pre-curated poetry corpus that our group made, as well as instructions on how to train a poem generator on this corpus and output a new poem.

#Repository contents
The repository contains our poetry corpus as a JSON file

#References
https://github.com/aparrish/gutenberg-poetry-corpus/blob/master/quick-experiments.ipynb  - Allison Parrish’s tutorial, with interacting with and basic analysis of the poetry corpus. Implemented Markov Chain Model Process from here. 

https://www.educative.io/blog/deep-learning-text-generation-markov-chains - Alternative article on Markov Chain text generation

